### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>

### ISSUE THREAD

**Issue by sigmareaver** [m4tx/jisho-scraper#1]
`UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>`
On Windows, this error occurs when exporting to csv.

The fix is to change this:
`with open(path, 'w', newline='') as csv_file:`
To this:
`with open(path, 'w', newline='', encoding='utf-8') as csv_file:`

**Comment by m4tx** [comment]
Fixed, thanks a lot!
